dataset-path-train: '/home/duyngu/Downloads/dataset_action_split/train.pkl'
dataset-path-test: '/home/duyngu/Downloads/dataset_action_split/test.pkl'
epochs: 500
project: 'runs'
batch-size: 384
img-size: 64
num-frame: 30

